#! /usr/bin/bash
# echo $PATH

# Opens a file with nano and makes a backup
# directory and folder.

# Use the command nanok <file>
# Modify /home/<user>/.bashrc to make nanok
# useable for the system or <user> by specifying
# the nanok file's location. This part in .bashrc
# export PATH=$PATH:/home/<user>/Desktop

# Opens file with nano.
nano $1
# echo $1

DIRECTORY="${1%/*}"
IN_FILE="${1##*/}"

# Checks for nested folder paths.
if [ "$DIRECTORY" != "$IN_FILE" ]; then
  BACKUP="$DIRECTORY/.nanok"
else
  # Otherwise it uses pwd ./.nanok.
  BACKUP="./.nanok"
fi
# The backup folder and file's location.
DATE=$(date "+%Y%m%d%H%M_")
OUT_FILE="$BACKUP/$DATE$IN_FILE"

# echo $BACKUP
# echo $OUT_FILE

# Make a directory if it doesn't exist,
# otherwise copy the backup into the directory.
if [ ! -d "$BACKUP" ]; then
  echo "Directory '$BACKUP' doesnt exist."
  mkdir -m 700 $BACKUP
  cp ./$1 $OUT_FILE
  echo "Directory and copy complete."
else
  echo "Directory '$BACKUP' exists, copying file"
  cp ./$1 $OUT_FILE
  echo "Copy complete"
fi
